use std::path::{Path, PathBuf};
use std::process::Command as StdCommand;

use anyhow::Context;

use backbeatin::{
    config::Config,
    store::{Store, unix_now},
    repo::{ResticBackend, BackupBackend, RestoreOutcome},
    verify::{compute_manifest, verify_restore},
    store::NewVerificationRun,
    verify::VerificationStatus,
    sign::{Signer, manifest_sha256, run_signing_message}
};

const MINIO_IMAGE: &str = "minio/minio:latest";
/// Fixed password for the synthetic demo repo so the demo is self-contained
/// (no interactive restic password prompt) and reproducible.
const DEMO_RESTIC_PASSWORD: &str = "backbeat-demo-password";

/// Run a full demo: create a synthetic repo, run verify against a healthy
/// snapshot, corrupt the repo, run verify against a corrupted snapshot,
/// then export the signed proof bundle.
pub async fn run_demo(output: &PathBuf) -> anyhow::Result<()> {
    tracing::info!("Pulling Docker images…");
    let _ = StdCommand::new("docker").args(["pull", "-q", MINIO_IMAGE]).output();

    // Start MinIO.
    let (port, minio_id) = start_minio()?;
    tracing::info!("MinIO started on port {}", port);

    let tmp = tempfile::tempdir().context("tempdir")?;
    // Host `restic` reaches MinIO via the published port.
    let repo_url = format!("s3:http://127.0.0.1:{}/backbeat-demo", port);
    let db_path = tmp.path().join("backbeat.db");
    let config_path = tmp.path().join("backbeat.toml");

    // Create config. The credential env vars are validated by `Config::load`
    // against the process environment, so they must be exported when running.
    let config_content = format!(
        "[[repo]]\nname = \"demo\"\nbackend = \"restic\"\nuri = \"{}\"\n[repo.credential_env_vars]\nAWS_ACCESS_KEY_ID = \"x\"\nAWS_SECRET_ACCESS_KEY = \"x\"\nRESTIC_PASSWORD = \"x\"\n",
        repo_url,
    );
    std::fs::write(&config_path, &config_content).context("write config")?;

    let store = Store::open(&db_path).context("open store")?;
    let signer = Signer::auto_load_or_generate().ok();

    // ── Phase 1: Healthy repo ──
    tracing::info!("── Phase 1: Healthy repo ──");
    run_restic(tmp.path(), &["init", "--repo", &repo_url])?;

    let healthy_dir = tmp.path().join("healthy-data");
    std::fs::create_dir_all(&healthy_dir)?;
    std::fs::write(healthy_dir.join("readme.txt"), b"Backbeatin demo: this is a healthy backup.\n")?;
    std::fs::write(healthy_dir.join("config.json"), br#"{"version":1,"env":"production"}"#)?;
    std::fs::write(healthy_dir.join("data.csv"), b"id,name,value\n1,alpha,100\n2,beta,200\n3,gamma,300\n")?;

    // Use a relative source path (cwd = tmp) so restic stores `healthy-data/`
    // rather than the full absolute path chain, keeping the snapshot small and
    // the restore landing cleanly under the target directory.
    run_restic(tmp.path(), &["backup", "--repo", &repo_url, "healthy-data"])?;
    tracing::info!("Healthy backup created");

    verify_and_store(&config_path, "demo", &store, &signer).await?;

    // ── Phase 2: Corrupted repo ──
    tracing::info!("── Phase 2: Corrupted repo ──");
    // Create a second snapshot with different data.
    let corrupt_dir = tmp.path().join("corrupt-data");
    std::fs::create_dir_all(&corrupt_dir)?;
    std::fs::write(corrupt_dir.join("secrets.txt"), b"Sensitive data")?;
    run_restic(tmp.path(), &["backup", "--repo", &repo_url, "corrupt-data"])?;

    // Corrupt the repo by deleting the restic index.
    let _ = StdCommand::new("docker")
        .args(["exec", &minio_id, "sh", "-c", "rm -rf /data/backbeat-demo/index"])
        .output();
    tracing::info!("Repo corrupted (index removed)");

    verify_and_store(&config_path, "demo", &store, &signer).await?;

    // ── Export ──
    let records = store.recent_runs("demo", 10)?;
    tracing::info!("Exporting {} runs…", records.len());

    let public_key_hex = signer.as_ref().map(|s| s.public_key_hex()).unwrap_or_default();

    let bundle = serde_json::json!({
        "version": 1,
        "created_at": unix_now(),
        "public_key": public_key_hex,
        "source": "backbeat demo -- generated by the real backbeat binary against a synthetic Restic repo hosted in a local MinIO instance",
        "runs": records.iter().map(|r| {
            serde_json::json!({
                "id": r.id,
                "repo_name": r.repo_name,
                "snapshot_id": r.snapshot_id,
                "status": r.status,
                "files_count": r.files_count,
                "bytes_restored": r.bytes_restored,
                "message": r.message,
                "signature_hex": r.signature_hex,
                "public_key_hex": r.public_key_hex,
                "started_at": r.started_at,
                "completed_at": r.completed_at,
            })
        }).collect::<Vec<_>>(),
    });

    let bundle_json = serde_json::to_string_pretty(&bundle)?;
    std::fs::write(output, &bundle_json)?;

    // Cleanup.
    stop_container(&minio_id);

    tracing::info!("Demo complete! Bundle written to: {}", output.display());
    println!("{}", bundle_json);

    Ok(())
}

async fn verify_and_store(config_path: &std::path::Path, repo_name: &str, store: &Store, signer: &Option<Signer>) -> anyhow::Result<()> {
    let config = Config::load(config_path)?;
    let repo_config = config.repos.iter().find(|r| r.name == repo_name)
        .ok_or_else(|| anyhow::anyhow!("Repo '{}' not found in config", repo_name))?;

    let started_at = unix_now();
    let backend = ResticBackend::from_config(repo_config)?;
    let snapshot_id = backend.latest_snapshot_id().await?;

    // Attempt restore — on failure, still record a "fail" run with the error.
    let tmp2 = tempfile::tempdir()?;
    let (_outcome, manifest_opt, status, message, files_count, bytes_restored) =
        match backend.restore_snapshot(&snapshot_id, tmp2.path()).await {
            Ok(oc) => {
                let files_count = oc.files_count;
                let bytes_restored = oc.bytes_restored;
                match compute_manifest(tmp2.path()) {
                    Ok(mf) => {
                        let result = verify_restore(&oc, &mf);
                        (oc, Some(mf), result.status, result.message,
                         files_count, bytes_restored)
                    }
                    Err(e) => {
                        let msg = format!("Manifest computation failed: {}", e);
                        tracing::warn!("  {}", msg);
                        (oc, None, VerificationStatus::Fail, msg,
                         files_count, bytes_restored)
                    }
                }
            }
            Err(e) => {
                let msg = format!("Restore failed: {}", e);
                tracing::warn!("  {}", msg);
                (RestoreOutcome {
                    snapshot_id: snapshot_id.clone(),
                    files_count: 0,
                    bytes_restored: 0,
                    count_is_meaningful: true,
                }, None, VerificationStatus::Fail, msg, 0u64, 0u64)
            }
        };
    let completed_at = unix_now();

    let run = NewVerificationRun {
        repo_name: repo_config.name.clone(),
        repo_backend: repo_config.backend.to_string(),
        repo_uri: repo_config.uri.clone(),
        snapshot_id: snapshot_id.clone(),
        status,
        files_count,
        bytes_restored,
        message: message.clone(),
        manifest: manifest_opt,
        signature_hex: None,
        public_key_hex: None,
        started_at,
        completed_at,
    };

    let run_id = store.insert_verification_run(&run)?;

    // Sign the run.
    if let Some(ref s) = signer {
        let manifest_hash = run.manifest.as_ref()
            .map(manifest_sha256)
            .unwrap_or_default();
        if let Ok(msg) = run_signing_message(
            run_id, &repo_config.name, &snapshot_id,
            if matches!(status, VerificationStatus::Pass) { "pass" } else { "fail" },
            files_count, bytes_restored, &message,
            &manifest_hash, started_at, completed_at,
        ) {
            let sig = s.sign(&msg);
            let pk = s.public_key_hex();
            store.update_run_signature(run_id, &sig, &pk).ok();
        }
    }

    tracing::info!("  Verify {}: {:?}", snapshot_id, status);
    Ok(())
}

// ── MinIO helpers ──

fn start_minio() -> anyhow::Result<(u16, String)> {
    let out = StdCommand::new("docker")
        .args(["run", "-d", "--rm", "-p", "9000",
            "-e", "MINIO_ROOT_USER=minioadmin",
            "-e", "MINIO_ROOT_PASSWORD=minioadmin",
            MINIO_IMAGE, "server", "/data"])
        .output()
        .expect("Docker required");
    if !out.status.success() {
        anyhow::bail!(
            "Failed to start MinIO container: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    let id = String::from_utf8(out.stdout)
        .context("docker run returned non-UTF-8 container ID")?
        .trim()
        .to_string();

    let port_out = StdCommand::new("docker")
        .args(["port", &id, "9000"])
        .output()
        .context("failed to run docker port")?;
    let port_str = String::from_utf8(port_out.stdout)
        .context("docker port returned non-UTF-8 output")?;
    // `docker port` may emit multiple bindings (e.g. `0.0.0.0:51832` and
    // `[::]:51832` on macOS/ipv6). Pick the first line whose trailing
    // `:`-separated token parses as a port.
    let port: u16 = port_str
        .lines()
        .find_map(|line| line.rsplit(':').next().and_then(|p| p.trim().parse().ok()))
        .expect("could not parse MinIO host port");
    std::thread::sleep(std::time::Duration::from_secs(2));
    Ok((port, id))
}

fn stop_container(id: &str) {
    let _ = StdCommand::new("docker").args(["rm", "-f", id]).output();
}

/// Run a `restic` command on the host, pointing at MinIO via the published
/// port. Using the host binary (rather than a dockerised restic) keeps the
/// demo consistent with `verify_and_store` (which also uses the host `restic`
/// via `ResticBackend`), and avoids the Docker-for-mac `--network host` and
/// bind-mount issues.
fn run_restic(cwd: &Path, args: &[&str]) -> anyhow::Result<()> {
    let out = StdCommand::new("restic")
        .current_dir(cwd)
        .env("AWS_ACCESS_KEY_ID", "minioadmin")
        .env("AWS_SECRET_ACCESS_KEY", "minioadmin")
        .env("RESTIC_PASSWORD", DEMO_RESTIC_PASSWORD)
        .args(args)
        .output()?;
    if !out.status.success() {
        anyhow::bail!("restic: {}", String::from_utf8_lossy(&out.stderr));
    }
    Ok(())
}
