use std::path::PathBuf;
use std::process::Command as StdCommand;

use anyhow::Context;

use backbeat_core::{Config, Store, ResticBackend, BackupBackend, compute_manifest, verify_restore, NewVerificationRun, VerificationStatus, Signer};

const MINIO_IMAGE: &str = "minio/minio:latest";
const RESTIC_IMAGE: &str = "restic/restic:latest";

/// Run a full demo: create a synthetic repo, run verify against a healthy
/// snapshot, corrupt the repo, run verify against a corrupted snapshot,
/// then export the signed proof bundle.
pub async fn run_demo(output: &PathBuf) -> anyhow::Result<()> {
    tracing::info!("Pulling Docker images…");
    let _ = StdCommand::new("docker").args(["pull", "-q", MINIO_IMAGE]).output();
    let _ = StdCommand::new("docker").args(["pull", "-q", RESTIC_IMAGE]).output();

    // Start MinIO.
    let (port, minio_id) = start_minio();
    tracing::info!("MinIO started on port {}", port);

    let tmp = tempfile::tempdir().context("tempdir")?;
    let repo_url = format!("s3:http://127.0.0.1:{}/backbeat-demo", port);
    let db_path = tmp.path().join("backbeat.db");
    let config_path = tmp.path().join("backbeat.toml");

    // Create config.
    let config_content = format!(
        "[[repo]]\nname = \"demo\"\nbackend = \"restic\"\nuri = \"{}\"\n[repo.credential_env_vars]\nAWS_ACCESS_KEY_ID = \"x\"\nAWS_SECRET_ACCESS_KEY = \"x\"\n",
        repo_url,
    );
    std::fs::write(&config_path, &config_content).context("write config")?;

    let store = Store::open(&db_path).context("open store")?;
    let signer = Signer::auto_load_or_generate().ok();

    // ── Phase 1: Healthy repo ──
    tracing::info!("── Phase 1: Healthy repo ──");
    run_restic(port, &["init", "--repo", &repo_url])?;

    let healthy_dir = tmp.path().join("healthy-data");
    std::fs::create_dir_all(&healthy_dir)?;
    std::fs::write(healthy_dir.join("readme.txt"), b"Backbeatin demo: this is a healthy backup.\n")?;
    std::fs::write(healthy_dir.join("config.json"), br#"{"version":1,"env":"production"}"#)?;
    std::fs::write(healthy_dir.join("data.csv"), b"id,name,value\n1,alpha,100\n2,beta,200\n3,gamma,300\n")?;

    run_restic(port, &["backup", "--repo", &repo_url, healthy_dir.to_str().unwrap()])?;
    tracing::info!("Healthy backup created");

    verify_and_store(&config_path, "demo", &store, &signer).await?;

    // ── Phase 2: Corrupted repo ──
    tracing::info!("── Phase 2: Corrupted repo ──");
    // Create a second snapshot with different data.
    let corrupt_dir = tmp.path().join("corrupt-data");
    std::fs::create_dir_all(&corrupt_dir)?;
    std::fs::write(corrupt_dir.join("secrets.txt"), b"Sensitive data")?;
    run_restic(port, &["backup", "--repo", &repo_url, corrupt_dir.to_str().unwrap()])?;

    // Corrupt the repo by deleting the restic index.
    let _ = StdCommand::new("docker")
        .args(["exec", &minio_id, "sh", "-c", "rm -rf /data/backbeat-demo/index"])
        .output();
    tracing::info!("Repo corrupted (index removed)");

    verify_and_store(&config_path, "demo", &store, &signer).await?;

    // ── Export ──
    let records = store.recent_runs("demo", 10)?;
    tracing::info!("Exporting {} runs…", records.len());

    let public_key_hex = signer.as_ref().map(|s| s.public_key_hex()).unwrap_or_default();

    let bundle = serde_json::json!({
        "version": 1,
        "created_at": backbeat_core::store::unix_now(),
        "public_key": public_key_hex,
        "source": "backbeat demo -- generated by the real backbeat binary against a synthetic Restic repo hosted in a local MinIO instance",
        "runs": records.iter().map(|r| {
            serde_json::json!({
                "id": r.id,
                "repo_name": r.repo_name,
                "snapshot_id": r.snapshot_id,
                "status": r.status,
                "files_count": r.files_count,
                "bytes_restored": r.bytes_restored,
                "message": r.message,
                "signature_hex": r.signature_hex,
                "public_key_hex": r.public_key_hex,
                "started_at": r.started_at,
                "completed_at": r.completed_at,
            })
        }).collect::<Vec<_>>(),
    });

    let bundle_json = serde_json::to_string_pretty(&bundle)?;
    std::fs::write(output, &bundle_json)?;

    // Cleanup.
    stop_container(&minio_id);

    tracing::info!("Demo complete! Bundle written to: {}", output.display());
    println!("{}", bundle_json);

    Ok(())
}

async fn verify_and_store(config_path: &std::path::Path, repo_name: &str, store: &Store, signer: &Option<Signer>) -> anyhow::Result<()> {
    let config = Config::load(config_path)?;
    let repo_config = config.repos.iter().find(|r| r.name == repo_name).unwrap();

    let started_at = backbeat_core::store::unix_now();
    let backend = ResticBackend::from_config(repo_config)?;
    let snapshot_id = backend.latest_snapshot_id().await?;

    let tmp2 = tempfile::tempdir()?;
    let outcome = backend.restore_snapshot(&snapshot_id, tmp2.path()).await?;
    let manifest = compute_manifest(tmp2.path())?;
    let result = verify_restore(&outcome, &manifest);
    let completed_at = backbeat_core::store::unix_now();

    let run = NewVerificationRun {
        repo_name: repo_config.name.clone(),
        repo_backend: format!("{:?}", repo_config.backend).to_lowercase(),
        repo_uri: repo_config.uri.clone(),
        snapshot_id: snapshot_id.clone(),
        status: result.status,
        files_count: outcome.files_count,
        bytes_restored: outcome.bytes_restored,
        message: result.message.clone(),
        manifest: Some(manifest),
        signature_hex: None,
        public_key_hex: None,
        started_at,
        completed_at,
    };

    let run_id = store.insert_verification_run(&run)?;

    // Sign the run.
    if let Some(ref s) = signer {
        let manifest_hash = run.manifest.as_ref()
            .map(backbeat_core::sign::manifest_sha256)
            .unwrap_or_default();
        if let Ok(msg) = backbeat_core::sign::run_signing_message(
            run_id, &repo_config.name, &snapshot_id,
            if matches!(result.status, VerificationStatus::Pass) { "pass" } else { "fail" },
            outcome.files_count, outcome.bytes_restored, &result.message,
            &manifest_hash, started_at, completed_at,
        ) {
            let sig = s.sign(&msg);
            let pk = s.public_key_hex();
            store.update_run_signature(run_id, &sig, &pk).ok();
        }
    }

    tracing::info!("  Verify {}: {:?}", snapshot_id, result.status);
    Ok(())
}

// ── MinIO helpers ──

fn start_minio() -> (u16, String) {
    let out = StdCommand::new("docker")
        .args(["run", "-d", "--rm", "-p", "9000",
            "-e", "MINIO_ROOT_USER=minioadmin",
            "-e", "MINIO_ROOT_PASSWORD=minioadmin",
            MINIO_IMAGE, "server", "/data"])
        .output()
        .expect("Docker required");
    assert!(out.status.success(), "minio start: {}", String::from_utf8_lossy(&out.stderr));
    let id = String::from_utf8(out.stdout).unwrap().trim().to_string();

    let port_out = StdCommand::new("docker")
        .args(["port", &id, "9000"])
        .output()
        .unwrap();
    let port_str = String::from_utf8(port_out.stdout).unwrap();
    let port: u16 = port_str.trim().split(':').nth(1).unwrap().parse().unwrap();
    std::thread::sleep(std::time::Duration::from_secs(2));
    (port, id)
}

fn stop_container(id: &str) {
    let _ = StdCommand::new("docker").args(["rm", "-f", id]).output();
}

fn run_restic(_port: u16, args: &[&str]) -> anyhow::Result<()> {
    let out = StdCommand::new("docker")
        .args(["run", "--rm", "--network", "host",
            "-e", "AWS_ACCESS_KEY_ID=minioadmin",
            "-e", "AWS_SECRET_ACCESS_KEY=minioadmin",
            RESTIC_IMAGE])
        .args(args)
        .output()?;
    if !out.status.success() {
        anyhow::bail!("restic: {}", String::from_utf8_lossy(&out.stderr));
    }
    Ok(())
}
